### ISSUE TITLE
Add other arguments to bash completion for ack

### ISSUE THREAD

**Issue by rpgoldman** [jonasbn/bash_completion_ack#1]
I have [a revised version](https://gist.github.com/rpgoldman/4febcea28074cc614a38ec1c2f3d4eef) of your bash completion, which got me started.

I've added the command line arguments from `ack`, and also have a new way of collecting the types, that collects both the standard ones and any that are added by the user's (or any other) `.ackrc`.

Hoping that this will be helpful to you and others.

**Comment by jonasbn** [comment]
hi @rpgoldman 

Is is possible for you to create a pull request? it is easier to handle

**Comment by rpgoldman** [comment]
OK, done!

**Comment by jonasbn** [comment]
This was fixed via PR #2
